#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgAbarrotesDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TiendaBD")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCliente(Cliente instance);
    partial void UpdateCliente(Cliente instance);
    partial void DeleteCliente(Cliente instance);
    partial void InsertDetalle_Inventario(Detalle_Inventario instance);
    partial void UpdateDetalle_Inventario(Detalle_Inventario instance);
    partial void DeleteDetalle_Inventario(Detalle_Inventario instance);
    partial void InsertInventarios(Inventarios instance);
    partial void UpdateInventarios(Inventarios instance);
    partial void DeleteInventarios(Inventarios instance);
    partial void InsertDetalle_Venta(Detalle_Venta instance);
    partial void UpdateDetalle_Venta(Detalle_Venta instance);
    partial void DeleteDetalle_Venta(Detalle_Venta instance);
    partial void InsertMetodo_Pago(Metodo_Pago instance);
    partial void UpdateMetodo_Pago(Metodo_Pago instance);
    partial void DeleteMetodo_Pago(Metodo_Pago instance);
    partial void InsertProducto(Producto instance);
    partial void UpdateProducto(Producto instance);
    partial void DeleteProducto(Producto instance);
    partial void InsertVenta(Venta instance);
    partial void UpdateVenta(Venta instance);
    partial void DeleteVenta(Venta instance);
    partial void InsertSaldos(Saldos instance);
    partial void UpdateSaldos(Saldos instance);
    partial void DeleteSaldos(Saldos instance);
    partial void InsertReportesVentas(ReportesVentas instance);
    partial void UpdateReportesVentas(ReportesVentas instance);
    partial void DeleteReportesVentas(ReportesVentas instance);
    partial void InsertReportesInventarios(ReportesInventarios instance);
    partial void UpdateReportesInventarios(ReportesInventarios instance);
    partial void DeleteReportesInventarios(ReportesInventarios instance);
    partial void InsertReportesCPP(ReportesCPP instance);
    partial void UpdateReportesCPP(ReportesCPP instance);
    partial void DeleteReportesCPP(ReportesCPP instance);
    partial void InsertProveedor(Proveedor instance);
    partial void UpdateProveedor(Proveedor instance);
    partial void DeleteProveedor(Proveedor instance);
    partial void InsertAuditoria(Auditoria instance);
    partial void UpdateAuditoria(Auditoria instance);
    partial void DeleteAuditoria(Auditoria instance);
    partial void InsertMovimientosDinero(MovimientosDinero instance);
    partial void UpdateMovimientosDinero(MovimientosDinero instance);
    partial void DeleteMovimientosDinero(MovimientosDinero instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ProgAbarrotesDB.Properties.Settings.Default.TiendaBDConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}

		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) :
				base(connection, mappingSource)
		{
			OnCreated();
		}


		// //

		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Cliente> Cliente
		{
			get
			{
				return this.GetTable<Cliente>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Inventario> Detalle_Inventario
		{
			get
			{
				return this.GetTable<Detalle_Inventario>();
			}
		}
		
		public System.Data.Linq.Table<Inventarios> Inventarios
		{
			get
			{
				return this.GetTable<Inventarios>();
			}
		}
		
		public System.Data.Linq.Table<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this.GetTable<Detalle_Venta>();
			}
		}
		
		public System.Data.Linq.Table<Metodo_Pago> Metodo_Pago
		{
			get
			{
				return this.GetTable<Metodo_Pago>();
			}
		}
		
		public System.Data.Linq.Table<Producto> Producto
		{
			get
			{
				return this.GetTable<Producto>();
			}
		}
		
		public System.Data.Linq.Table<Venta> Venta
		{
			get
			{
				return this.GetTable<Venta>();
			}
		}
		
		public System.Data.Linq.Table<Saldos> Saldos
		{
			get
			{
				return this.GetTable<Saldos>();
			}
		}
		
		public System.Data.Linq.Table<ReportesVentas> ReportesVentas
		{
			get
			{
				return this.GetTable<ReportesVentas>();
			}
		}
		
		public System.Data.Linq.Table<ReportesInventarios> ReportesInventarios
		{
			get
			{
				return this.GetTable<ReportesInventarios>();
			}
		}
		
		public System.Data.Linq.Table<ReportesCPP> ReportesCPP
		{
			get
			{
				return this.GetTable<ReportesCPP>();
			}
		}
		
		public System.Data.Linq.Table<Proveedor> Proveedor
		{
			get
			{
				return this.GetTable<Proveedor>();
			}
		}
		
		public System.Data.Linq.Table<Auditoria> Auditoria
		{
			get
			{
				return this.GetTable<Auditoria>();
			}
		}
		
		public System.Data.Linq.Table<MovimientosDinero> MovimientosDinero
		{
			get
			{
				return this.GetTable<MovimientosDinero>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Cliente")]
	public partial class Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Cliente;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private EntitySet<Detalle_Venta> _Detalle_Venta;
		
		private EntitySet<Venta> _Venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ClienteChanging(int value);
    partial void OnID_ClienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    #endregion
		
		public Cliente()
		{
			this._Detalle_Venta = new EntitySet<Detalle_Venta>(new Action<Detalle_Venta>(this.attach_Detalle_Venta), new Action<Detalle_Venta>(this.detach_Detalle_Venta));
			this._Venta = new EntitySet<Venta>(new Action<Venta>(this.attach_Venta), new Action<Venta>(this.detach_Venta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Detalle_Venta", Storage="_Detalle_Venta", ThisKey="ID_Cliente", OtherKey="ID_Cliente")]
		public EntitySet<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this._Detalle_Venta;
			}
			set
			{
				this._Detalle_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venta", Storage="_Venta", ThisKey="ID_Cliente", OtherKey="ID_Cliente")]
		public EntitySet<Venta> Venta
		{
			get
			{
				return this._Venta;
			}
			set
			{
				this._Venta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
		
		private void attach_Venta(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = this;
		}
		
		private void detach_Venta(Venta entity)
		{
			this.SendPropertyChanging();
			entity.Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Inventario")]
	public partial class Detalle_Inventario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Inventario;
		
		private int _ID_Producto;
		
		private int _Cantidad_Entrante;
		
		private decimal _Costo_Unitario;
		
		private System.Nullable<decimal> _Subtotal;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_InventarioChanging(int value);
    partial void OnID_InventarioChanged();
    partial void OnID_ProductoChanging(int value);
    partial void OnID_ProductoChanged();
    partial void OnCantidad_EntranteChanging(int value);
    partial void OnCantidad_EntranteChanged();
    partial void OnCosto_UnitarioChanging(decimal value);
    partial void OnCosto_UnitarioChanged();
    partial void OnSubtotalChanging(System.Nullable<decimal> value);
    partial void OnSubtotalChanged();
    #endregion
		
		public Detalle_Inventario()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Inventario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Inventario
		{
			get
			{
				return this._ID_Inventario;
			}
			set
			{
				if ((this._ID_Inventario != value))
				{
					this.OnID_InventarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Inventario = value;
					this.SendPropertyChanged("ID_Inventario");
					this.OnID_InventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int NOT NULL")]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Entrante", DbType="Int NOT NULL")]
		public int Cantidad_Entrante
		{
			get
			{
				return this._Cantidad_Entrante;
			}
			set
			{
				if ((this._Cantidad_Entrante != value))
				{
					this.OnCantidad_EntranteChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Entrante = value;
					this.SendPropertyChanged("Cantidad_Entrante");
					this.OnCantidad_EntranteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Costo_Unitario", DbType="Decimal(10,2) NOT NULL")]
		public decimal Costo_Unitario
		{
			get
			{
				return this._Costo_Unitario;
			}
			set
			{
				if ((this._Costo_Unitario != value))
				{
					this.OnCosto_UnitarioChanging(value);
					this.SendPropertyChanging();
					this._Costo_Unitario = value;
					this.SendPropertyChanged("Costo_Unitario");
					this.OnCosto_UnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", AutoSync=AutoSync.Always, DbType="Decimal(21,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Inventario", Storage="_Producto", ThisKey="ID_Producto", OtherKey="ID_Producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Inventario.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Inventario.Add(this);
						this._ID_Producto = value.ID_Producto;
					}
					else
					{
						this._ID_Producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Inventarios")]
	public partial class Inventarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Inventario;
		
		private System.Nullable<int> _ID_Producto;
		
		private System.Nullable<int> _ID_Proveedor;
		
		private System.Nullable<System.DateTime> _FechaEntrada;
		
		private System.Nullable<int> _CantidadEntrada;
		
		private System.Nullable<decimal> _PrecioPorUnidad;
		
		private System.Nullable<decimal> _Total;
		
		private string _Observaciones;
		
		private System.Nullable<System.DateTime> _FechaRegistro;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Proveedor> _Proveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_InventarioChanging(int value);
    partial void OnID_InventarioChanged();
    partial void OnID_ProductoChanging(System.Nullable<int> value);
    partial void OnID_ProductoChanged();
    partial void OnID_ProveedorChanging(System.Nullable<int> value);
    partial void OnID_ProveedorChanged();
    partial void OnFechaEntradaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEntradaChanged();
    partial void OnCantidadEntradaChanging(System.Nullable<int> value);
    partial void OnCantidadEntradaChanged();
    partial void OnPrecioPorUnidadChanging(System.Nullable<decimal> value);
    partial void OnPrecioPorUnidadChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnObservacionesChanging(string value);
    partial void OnObservacionesChanged();
    partial void OnFechaRegistroChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaRegistroChanged();
    #endregion
		
		public Inventarios()
		{
			this._Producto = default(EntityRef<Producto>);
			this._Proveedor = default(EntityRef<Proveedor>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Inventario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Inventario
		{
			get
			{
				return this._ID_Inventario;
			}
			set
			{
				if ((this._ID_Inventario != value))
				{
					this.OnID_InventarioChanging(value);
					this.SendPropertyChanging();
					this._ID_Inventario = value;
					this.SendPropertyChanged("ID_Inventario");
					this.OnID_InventarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int")]
		public System.Nullable<int> ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Proveedor", DbType="Int")]
		public System.Nullable<int> ID_Proveedor
		{
			get
			{
				return this._ID_Proveedor;
			}
			set
			{
				if ((this._ID_Proveedor != value))
				{
					if (this._Proveedor.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProveedorChanging(value);
					this.SendPropertyChanging();
					this._ID_Proveedor = value;
					this.SendPropertyChanged("ID_Proveedor");
					this.OnID_ProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="Date")]
		public System.Nullable<System.DateTime> FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this.OnFechaEntradaChanging(value);
					this.SendPropertyChanging();
					this._FechaEntrada = value;
					this.SendPropertyChanged("FechaEntrada");
					this.OnFechaEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadEntrada", DbType="Int")]
		public System.Nullable<int> CantidadEntrada
		{
			get
			{
				return this._CantidadEntrada;
			}
			set
			{
				if ((this._CantidadEntrada != value))
				{
					this.OnCantidadEntradaChanging(value);
					this.SendPropertyChanging();
					this._CantidadEntrada = value;
					this.SendPropertyChanged("CantidadEntrada");
					this.OnCantidadEntradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioPorUnidad", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PrecioPorUnidad
		{
			get
			{
				return this._PrecioPorUnidad;
			}
			set
			{
				if ((this._PrecioPorUnidad != value))
				{
					this.OnPrecioPorUnidadChanging(value);
					this.SendPropertyChanging();
					this._PrecioPorUnidad = value;
					this.SendPropertyChanged("PrecioPorUnidad");
					this.OnPrecioPorUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciones", DbType="NVarChar(255)")]
		public string Observaciones
		{
			get
			{
				return this._Observaciones;
			}
			set
			{
				if ((this._Observaciones != value))
				{
					this.OnObservacionesChanging(value);
					this.SendPropertyChanging();
					this._Observaciones = value;
					this.SendPropertyChanged("Observaciones");
					this.OnObservacionesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaRegistro", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaRegistro
		{
			get
			{
				return this._FechaRegistro;
			}
			set
			{
				if ((this._FechaRegistro != value))
				{
					this.OnFechaRegistroChanging(value);
					this.SendPropertyChanging();
					this._FechaRegistro = value;
					this.SendPropertyChanged("FechaRegistro");
					this.OnFechaRegistroChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Inventarios", Storage="_Producto", ThisKey="ID_Producto", OtherKey="ID_Producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Inventarios.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Inventarios.Add(this);
						this._ID_Producto = value.ID_Producto;
					}
					else
					{
						this._ID_Producto = default(Nullable<int>);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Inventarios", Storage="_Proveedor", ThisKey="ID_Proveedor", OtherKey="ID_Proveedor", IsForeignKey=true)]
		public Proveedor Proveedor
		{
			get
			{
				return this._Proveedor.Entity;
			}
			set
			{
				Proveedor previousValue = this._Proveedor.Entity;
				if (((previousValue != value) 
							|| (this._Proveedor.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Proveedor.Entity = null;
						previousValue.Inventarios.Remove(this);
					}
					this._Proveedor.Entity = value;
					if ((value != null))
					{
						value.Inventarios.Add(this);
						this._ID_Proveedor = value.ID_Proveedor;
					}
					else
					{
						this._ID_Proveedor = default(Nullable<int>);
					}
					this.SendPropertyChanged("Proveedor");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Detalle_Venta")]
	public partial class Detalle_Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Venta;
		
		private int _ID_Producto;
		
		private int _Cantidad;
		
		private decimal _Precio_Unitario;
		
		private System.Nullable<decimal> _Subtotal;
		
		private System.Nullable<int> _ID_Cliente;
		
		private EntityRef<Cliente> _Cliente;
		
		private EntityRef<Producto> _Producto;
		
		private EntityRef<Venta> _Venta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VentaChanging(int value);
    partial void OnID_VentaChanged();
    partial void OnID_ProductoChanging(int value);
    partial void OnID_ProductoChanged();
    partial void OnCantidadChanging(int value);
    partial void OnCantidadChanged();
    partial void OnPrecio_UnitarioChanging(decimal value);
    partial void OnPrecio_UnitarioChanged();
    partial void OnSubtotalChanging(System.Nullable<decimal> value);
    partial void OnSubtotalChanged();
    partial void OnID_ClienteChanging(System.Nullable<int> value);
    partial void OnID_ClienteChanged();
    #endregion
		
		public Detalle_Venta()
		{
			this._Cliente = default(EntityRef<Cliente>);
			this._Producto = default(EntityRef<Producto>);
			this._Venta = default(EntityRef<Venta>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Venta", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Venta
		{
			get
			{
				return this._ID_Venta;
			}
			set
			{
				if ((this._ID_Venta != value))
				{
					if (this._Venta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VentaChanging(value);
					this.SendPropertyChanging();
					this._ID_Venta = value;
					this.SendPropertyChanged("ID_Venta");
					this.OnID_VentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Unitario", DbType="Decimal(10,2) NOT NULL")]
		public decimal Precio_Unitario
		{
			get
			{
				return this._Precio_Unitario;
			}
			set
			{
				if ((this._Precio_Unitario != value))
				{
					this.OnPrecio_UnitarioChanging(value);
					this.SendPropertyChanging();
					this._Precio_Unitario = value;
					this.SendPropertyChanged("Precio_Unitario");
					this.OnPrecio_UnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subtotal", AutoSync=AutoSync.Always, DbType="Decimal(21,2)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<decimal> Subtotal
		{
			get
			{
				return this._Subtotal;
			}
			set
			{
				if ((this._Subtotal != value))
				{
					this.OnSubtotalChanging(value);
					this.SendPropertyChanging();
					this._Subtotal = value;
					this.SendPropertyChanged("Subtotal");
					this.OnSubtotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", DbType="Int")]
		public System.Nullable<int> ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Detalle_Venta", Storage="_Cliente", ThisKey="ID_Cliente", OtherKey="ID_Cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Detalle_Venta.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Detalle_Venta.Add(this);
						this._ID_Cliente = value.ID_Cliente;
					}
					else
					{
						this._ID_Cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Venta", Storage="_Producto", ThisKey="ID_Producto", OtherKey="ID_Producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Detalle_Venta.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Detalle_Venta.Add(this);
						this._ID_Producto = value.ID_Producto;
					}
					else
					{
						this._ID_Producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venta_Detalle_Venta", Storage="_Venta", ThisKey="ID_Venta", OtherKey="ID_Venta", IsForeignKey=true)]
		public Venta Venta
		{
			get
			{
				return this._Venta.Entity;
			}
			set
			{
				Venta previousValue = this._Venta.Entity;
				if (((previousValue != value) 
							|| (this._Venta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Venta.Entity = null;
						previousValue.Detalle_Venta.Remove(this);
					}
					this._Venta.Entity = value;
					if ((value != null))
					{
						value.Detalle_Venta.Add(this);
						this._ID_Venta = value.ID_Venta;
					}
					else
					{
						this._ID_Venta = default(int);
					}
					this.SendPropertyChanged("Venta");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Metodo_Pago")]
	public partial class Metodo_Pago : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Metodo;
		
		private string _Nombre;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MetodoChanging(int value);
    partial void OnID_MetodoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public Metodo_Pago()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Metodo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Metodo
		{
			get
			{
				return this._ID_Metodo;
			}
			set
			{
				if ((this._ID_Metodo != value))
				{
					this.OnID_MetodoChanging(value);
					this.SendPropertyChanging();
					this._ID_Metodo = value;
					this.SendPropertyChanged("ID_Metodo");
					this.OnID_MetodoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Producto")]
	public partial class Producto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Producto;
		
		private string _Nombre;
		
		private decimal _Precio;
		
		private string _Descripcion;
		
		private System.Nullable<int> _Stock;
		
		private EntitySet<Detalle_Inventario> _Detalle_Inventario;
		
		private EntitySet<Inventarios> _Inventarios;
		
		private EntitySet<Detalle_Venta> _Detalle_Venta;
		
		private EntitySet<Saldos> _Saldos;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProductoChanging(int value);
    partial void OnID_ProductoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnStockChanging(System.Nullable<int> value);
    partial void OnStockChanged();
    #endregion
		
		public Producto()
		{
			this._Detalle_Inventario = new EntitySet<Detalle_Inventario>(new Action<Detalle_Inventario>(this.attach_Detalle_Inventario), new Action<Detalle_Inventario>(this.detach_Detalle_Inventario));
			this._Inventarios = new EntitySet<Inventarios>(new Action<Inventarios>(this.attach_Inventarios), new Action<Inventarios>(this.detach_Inventarios));
			this._Detalle_Venta = new EntitySet<Detalle_Venta>(new Action<Detalle_Venta>(this.attach_Detalle_Venta), new Action<Detalle_Venta>(this.detach_Detalle_Venta));
			this._Saldos = new EntitySet<Saldos>(new Action<Saldos>(this.attach_Saldos), new Action<Saldos>(this.detach_Saldos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(10,2) NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Inventario", Storage="_Detalle_Inventario", ThisKey="ID_Producto", OtherKey="ID_Producto")]
		public EntitySet<Detalle_Inventario> Detalle_Inventario
		{
			get
			{
				return this._Detalle_Inventario;
			}
			set
			{
				this._Detalle_Inventario.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Inventarios", Storage="_Inventarios", ThisKey="ID_Producto", OtherKey="ID_Producto")]
		public EntitySet<Inventarios> Inventarios
		{
			get
			{
				return this._Inventarios;
			}
			set
			{
				this._Inventarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Detalle_Venta", Storage="_Detalle_Venta", ThisKey="ID_Producto", OtherKey="ID_Producto")]
		public EntitySet<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this._Detalle_Venta;
			}
			set
			{
				this._Detalle_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Saldos", Storage="_Saldos", ThisKey="ID_Producto", OtherKey="ID_Producto")]
		public EntitySet<Saldos> Saldos
		{
			get
			{
				return this._Saldos;
			}
			set
			{
				this._Saldos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Inventario(Detalle_Inventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Inventario(Detalle_Inventario entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Inventarios(Inventarios entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Inventarios(Inventarios entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
		
		private void attach_Saldos(Saldos entity)
		{
			this.SendPropertyChanging();
			entity.Producto = this;
		}
		
		private void detach_Saldos(Saldos entity)
		{
			this.SendPropertyChanging();
			entity.Producto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Venta")]
	public partial class Venta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Venta;
		
		private System.DateTime _Fecha;
		
		private System.Nullable<decimal> _Importe;
		
		private System.Nullable<decimal> _IVA;
		
		private System.Nullable<decimal> _Total;
		
		private string _Metodo_Pago;
		
		private System.Nullable<int> _ID_Cliente;
		
		private EntitySet<Detalle_Venta> _Detalle_Venta;
		
		private EntityRef<Cliente> _Cliente;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VentaChanging(int value);
    partial void OnID_VentaChanged();
    partial void OnFechaChanging(System.DateTime value);
    partial void OnFechaChanged();
    partial void OnImporteChanging(System.Nullable<decimal> value);
    partial void OnImporteChanged();
    partial void OnIVAChanging(System.Nullable<decimal> value);
    partial void OnIVAChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnMetodo_PagoChanging(string value);
    partial void OnMetodo_PagoChanged();
    partial void OnID_ClienteChanging(System.Nullable<int> value);
    partial void OnID_ClienteChanged();
    #endregion
		
		public Venta()
		{
			this._Detalle_Venta = new EntitySet<Detalle_Venta>(new Action<Detalle_Venta>(this.attach_Detalle_Venta), new Action<Detalle_Venta>(this.detach_Detalle_Venta));
			this._Cliente = default(EntityRef<Cliente>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Venta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Venta
		{
			get
			{
				return this._ID_Venta;
			}
			set
			{
				if ((this._ID_Venta != value))
				{
					this.OnID_VentaChanging(value);
					this.SendPropertyChanging();
					this._ID_Venta = value;
					this.SendPropertyChanged("ID_Venta");
					this.OnID_VentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date NOT NULL")]
		public System.DateTime Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Importe", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Importe
		{
			get
			{
				return this._Importe;
			}
			set
			{
				if ((this._Importe != value))
				{
					this.OnImporteChanging(value);
					this.SendPropertyChanging();
					this._Importe = value;
					this.SendPropertyChanged("Importe");
					this.OnImporteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IVA", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> IVA
		{
			get
			{
				return this._IVA;
			}
			set
			{
				if ((this._IVA != value))
				{
					this.OnIVAChanging(value);
					this.SendPropertyChanging();
					this._IVA = value;
					this.SendPropertyChanged("IVA");
					this.OnIVAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Metodo_Pago", DbType="NVarChar(50)")]
		public string Metodo_Pago
		{
			get
			{
				return this._Metodo_Pago;
			}
			set
			{
				if ((this._Metodo_Pago != value))
				{
					this.OnMetodo_PagoChanging(value);
					this.SendPropertyChanging();
					this._Metodo_Pago = value;
					this.SendPropertyChanged("Metodo_Pago");
					this.OnMetodo_PagoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Cliente", DbType="Int")]
		public System.Nullable<int> ID_Cliente
		{
			get
			{
				return this._ID_Cliente;
			}
			set
			{
				if ((this._ID_Cliente != value))
				{
					if (this._Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ClienteChanging(value);
					this.SendPropertyChanging();
					this._ID_Cliente = value;
					this.SendPropertyChanged("ID_Cliente");
					this.OnID_ClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Venta_Detalle_Venta", Storage="_Detalle_Venta", ThisKey="ID_Venta", OtherKey="ID_Venta")]
		public EntitySet<Detalle_Venta> Detalle_Venta
		{
			get
			{
				return this._Detalle_Venta;
			}
			set
			{
				this._Detalle_Venta.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Cliente_Venta", Storage="_Cliente", ThisKey="ID_Cliente", OtherKey="ID_Cliente", IsForeignKey=true)]
		public Cliente Cliente
		{
			get
			{
				return this._Cliente.Entity;
			}
			set
			{
				Cliente previousValue = this._Cliente.Entity;
				if (((previousValue != value) 
							|| (this._Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Cliente.Entity = null;
						previousValue.Venta.Remove(this);
					}
					this._Cliente.Entity = value;
					if ((value != null))
					{
						value.Venta.Add(this);
						this._ID_Cliente = value.ID_Cliente;
					}
					else
					{
						this._ID_Cliente = default(Nullable<int>);
					}
					this.SendPropertyChanged("Cliente");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Venta = this;
		}
		
		private void detach_Detalle_Venta(Detalle_Venta entity)
		{
			this.SendPropertyChanging();
			entity.Venta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Saldos")]
	public partial class Saldos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Saldo;
		
		private int _ID_Producto;
		
		private System.Nullable<int> _Cantidad_Entrante;
		
		private System.Nullable<int> _Cantidad_Salida;
		
		private System.Nullable<int> _Cantidad_Disponible;
		
		private EntityRef<Producto> _Producto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SaldoChanging(int value);
    partial void OnID_SaldoChanged();
    partial void OnID_ProductoChanging(int value);
    partial void OnID_ProductoChanged();
    partial void OnCantidad_EntranteChanging(System.Nullable<int> value);
    partial void OnCantidad_EntranteChanged();
    partial void OnCantidad_SalidaChanging(System.Nullable<int> value);
    partial void OnCantidad_SalidaChanged();
    partial void OnCantidad_DisponibleChanging(System.Nullable<int> value);
    partial void OnCantidad_DisponibleChanged();
    #endregion
		
		public Saldos()
		{
			this._Producto = default(EntityRef<Producto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Saldo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Saldo
		{
			get
			{
				return this._ID_Saldo;
			}
			set
			{
				if ((this._ID_Saldo != value))
				{
					this.OnID_SaldoChanging(value);
					this.SendPropertyChanging();
					this._ID_Saldo = value;
					this.SendPropertyChanged("ID_Saldo");
					this.OnID_SaldoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Producto", DbType="Int NOT NULL")]
		public int ID_Producto
		{
			get
			{
				return this._ID_Producto;
			}
			set
			{
				if ((this._ID_Producto != value))
				{
					if (this._Producto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_ProductoChanging(value);
					this.SendPropertyChanging();
					this._ID_Producto = value;
					this.SendPropertyChanged("ID_Producto");
					this.OnID_ProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Entrante", DbType="Int")]
		public System.Nullable<int> Cantidad_Entrante
		{
			get
			{
				return this._Cantidad_Entrante;
			}
			set
			{
				if ((this._Cantidad_Entrante != value))
				{
					this.OnCantidad_EntranteChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Entrante = value;
					this.SendPropertyChanged("Cantidad_Entrante");
					this.OnCantidad_EntranteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Salida", DbType="Int")]
		public System.Nullable<int> Cantidad_Salida
		{
			get
			{
				return this._Cantidad_Salida;
			}
			set
			{
				if ((this._Cantidad_Salida != value))
				{
					this.OnCantidad_SalidaChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Salida = value;
					this.SendPropertyChanged("Cantidad_Salida");
					this.OnCantidad_SalidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad_Disponible", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> Cantidad_Disponible
		{
			get
			{
				return this._Cantidad_Disponible;
			}
			set
			{
				if ((this._Cantidad_Disponible != value))
				{
					this.OnCantidad_DisponibleChanging(value);
					this.SendPropertyChanging();
					this._Cantidad_Disponible = value;
					this.SendPropertyChanged("Cantidad_Disponible");
					this.OnCantidad_DisponibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Producto_Saldos", Storage="_Producto", ThisKey="ID_Producto", OtherKey="ID_Producto", IsForeignKey=true)]
		public Producto Producto
		{
			get
			{
				return this._Producto.Entity;
			}
			set
			{
				Producto previousValue = this._Producto.Entity;
				if (((previousValue != value) 
							|| (this._Producto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Producto.Entity = null;
						previousValue.Saldos.Remove(this);
					}
					this._Producto.Entity = value;
					if ((value != null))
					{
						value.Saldos.Add(this);
						this._ID_Producto = value.ID_Producto;
					}
					else
					{
						this._ID_Producto = default(int);
					}
					this.SendPropertyChanged("Producto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportesVentas")]
	public partial class ReportesVentas : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ReporteVenta;
		
		private string _Cliente;
		
		private string _Producto;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _Total;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReporteVentaChanging(int value);
    partial void OnID_ReporteVentaChanged();
    partial void OnClienteChanging(string value);
    partial void OnClienteChanged();
    partial void OnProductoChanging(string value);
    partial void OnProductoChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public ReportesVentas()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ReporteVenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ReporteVenta
		{
			get
			{
				return this._ID_ReporteVenta;
			}
			set
			{
				if ((this._ID_ReporteVenta != value))
				{
					this.OnID_ReporteVentaChanging(value);
					this.SendPropertyChanging();
					this._ID_ReporteVenta = value;
					this.SendPropertyChanged("ID_ReporteVenta");
					this.OnID_ReporteVentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="NVarChar(100)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(100)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportesInventarios")]
	public partial class ReportesInventarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Producto;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _PrecioUnitario;
		
		private System.Nullable<decimal> _Total;
		
		private string _Proveedor;
		
		private System.Nullable<System.DateTime> _Fecha;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnProductoChanging(string value);
    partial void OnProductoChanged();
    partial void OnCantidadChanging(System.Nullable<int> value);
    partial void OnCantidadChanged();
    partial void OnPrecioUnitarioChanging(System.Nullable<decimal> value);
    partial void OnPrecioUnitarioChanged();
    partial void OnTotalChanging(System.Nullable<decimal> value);
    partial void OnTotalChanged();
    partial void OnProveedorChanging(string value);
    partial void OnProveedorChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    #endregion
		
		public ReportesInventarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(255)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this.OnCantidadChanging(value);
					this.SendPropertyChanging();
					this._Cantidad = value;
					this.SendPropertyChanged("Cantidad");
					this.OnCantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioUnitario", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> PrecioUnitario
		{
			get
			{
				return this._PrecioUnitario;
			}
			set
			{
				if ((this._PrecioUnitario != value))
				{
					this.OnPrecioUnitarioChanging(value);
					this.SendPropertyChanging();
					this._PrecioUnitario = value;
					this.SendPropertyChanged("PrecioUnitario");
					this.OnPrecioUnitarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this.OnTotalChanging(value);
					this.SendPropertyChanging();
					this._Total = value;
					this.SendPropertyChanged("Total");
					this.OnTotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="NVarChar(255)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this.OnProveedorChanging(value);
					this.SendPropertyChanging();
					this._Proveedor = value;
					this.SendPropertyChanged("Proveedor");
					this.OnProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ReportesCPP")]
	public partial class ReportesCPP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_ReporteCPP;
		
		private string _Cliente;
		
		private string _Nombre;
		
		private string _Proveedor;
		
		private string _Producto;
		
		private System.Nullable<int> _Stock;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ReporteCPPChanging(int value);
    partial void OnID_ReporteCPPChanged();
    partial void OnClienteChanging(string value);
    partial void OnClienteChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnProveedorChanging(string value);
    partial void OnProveedorChanged();
    partial void OnProductoChanging(string value);
    partial void OnProductoChanged();
    partial void OnStockChanging(System.Nullable<int> value);
    partial void OnStockChanged();
    #endregion
		
		public ReportesCPP()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_ReporteCPP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_ReporteCPP
		{
			get
			{
				return this._ID_ReporteCPP;
			}
			set
			{
				if ((this._ID_ReporteCPP != value))
				{
					this.OnID_ReporteCPPChanging(value);
					this.SendPropertyChanging();
					this._ID_ReporteCPP = value;
					this.SendPropertyChanged("ID_ReporteCPP");
					this.OnID_ReporteCPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cliente", DbType="NVarChar(100)")]
		public string Cliente
		{
			get
			{
				return this._Cliente;
			}
			set
			{
				if ((this._Cliente != value))
				{
					this.OnClienteChanging(value);
					this.SendPropertyChanging();
					this._Cliente = value;
					this.SendPropertyChanged("Cliente");
					this.OnClienteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proveedor", DbType="NVarChar(100)")]
		public string Proveedor
		{
			get
			{
				return this._Proveedor;
			}
			set
			{
				if ((this._Proveedor != value))
				{
					this.OnProveedorChanging(value);
					this.SendPropertyChanging();
					this._Proveedor = value;
					this.SendPropertyChanged("Proveedor");
					this.OnProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="NVarChar(100)")]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this.OnProductoChanging(value);
					this.SendPropertyChanging();
					this._Producto = value;
					this.SendPropertyChanged("Producto");
					this.OnProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Stock", DbType="Int")]
		public System.Nullable<int> Stock
		{
			get
			{
				return this._Stock;
			}
			set
			{
				if ((this._Stock != value))
				{
					this.OnStockChanging(value);
					this.SendPropertyChanging();
					this._Stock = value;
					this.SendPropertyChanged("Stock");
					this.OnStockChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedor")]
	public partial class Proveedor : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Proveedor;
		
		private string _Nombre;
		
		private string _Telefono;
		
		private string _Direccion;
		
		private EntitySet<Inventarios> _Inventarios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_ProveedorChanging(int value);
    partial void OnID_ProveedorChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    #endregion
		
		public Proveedor()
		{
			this._Inventarios = new EntitySet<Inventarios>(new Action<Inventarios>(this.attach_Inventarios), new Action<Inventarios>(this.detach_Inventarios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Proveedor", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Proveedor
		{
			get
			{
				return this._ID_Proveedor;
			}
			set
			{
				if ((this._ID_Proveedor != value))
				{
					this.OnID_ProveedorChanging(value);
					this.SendPropertyChanging();
					this._ID_Proveedor = value;
					this.SendPropertyChanged("ID_Proveedor");
					this.OnID_ProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="VarChar(20)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(255)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Proveedor_Inventarios", Storage="_Inventarios", ThisKey="ID_Proveedor", OtherKey="ID_Proveedor")]
		public EntitySet<Inventarios> Inventarios
		{
			get
			{
				return this._Inventarios;
			}
			set
			{
				this._Inventarios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Inventarios(Inventarios entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = this;
		}
		
		private void detach_Inventarios(Inventarios entity)
		{
			this.SendPropertyChanging();
			entity.Proveedor = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Auditoria")]
	public partial class Auditoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Auditoria;
		
		private string _UsuarioSQL;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _TablaAfectada;
		
		private System.Nullable<int> _FolioEliminado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_AuditoriaChanging(int value);
    partial void OnID_AuditoriaChanged();
    partial void OnUsuarioSQLChanging(string value);
    partial void OnUsuarioSQLChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnTablaAfectadaChanging(string value);
    partial void OnTablaAfectadaChanged();
    partial void OnFolioEliminadoChanging(System.Nullable<int> value);
    partial void OnFolioEliminadoChanged();
    #endregion
		
		public Auditoria()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Auditoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Auditoria
		{
			get
			{
				return this._ID_Auditoria;
			}
			set
			{
				if ((this._ID_Auditoria != value))
				{
					this.OnID_AuditoriaChanging(value);
					this.SendPropertyChanging();
					this._ID_Auditoria = value;
					this.SendPropertyChanged("ID_Auditoria");
					this.OnID_AuditoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsuarioSQL", DbType="NVarChar(100)")]
		public string UsuarioSQL
		{
			get
			{
				return this._UsuarioSQL;
			}
			set
			{
				if ((this._UsuarioSQL != value))
				{
					this.OnUsuarioSQLChanging(value);
					this.SendPropertyChanging();
					this._UsuarioSQL = value;
					this.SendPropertyChanged("UsuarioSQL");
					this.OnUsuarioSQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TablaAfectada", DbType="NVarChar(100)")]
		public string TablaAfectada
		{
			get
			{
				return this._TablaAfectada;
			}
			set
			{
				if ((this._TablaAfectada != value))
				{
					this.OnTablaAfectadaChanging(value);
					this.SendPropertyChanging();
					this._TablaAfectada = value;
					this.SendPropertyChanged("TablaAfectada");
					this.OnTablaAfectadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FolioEliminado", DbType="Int")]
		public System.Nullable<int> FolioEliminado
		{
			get
			{
				return this._FolioEliminado;
			}
			set
			{
				if ((this._FolioEliminado != value))
				{
					this.OnFolioEliminadoChanging(value);
					this.SendPropertyChanging();
					this._FolioEliminado = value;
					this.SendPropertyChanged("FolioEliminado");
					this.OnFolioEliminadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MovimientosDinero")]
	public partial class MovimientosDinero : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Movimiento;
		
		private System.Nullable<System.DateTime> _Fecha;
		
		private string _Movimiento;
		
		private System.Nullable<decimal> _MontoTotal;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MovimientoChanging(int value);
    partial void OnID_MovimientoChanged();
    partial void OnFechaChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaChanged();
    partial void OnMovimientoChanging(string value);
    partial void OnMovimientoChanged();
    partial void OnMontoTotalChanging(System.Nullable<decimal> value);
    partial void OnMontoTotalChanged();
    #endregion
		
		public MovimientosDinero()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Movimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Movimiento
		{
			get
			{
				return this._ID_Movimiento;
			}
			set
			{
				if ((this._ID_Movimiento != value))
				{
					this.OnID_MovimientoChanging(value);
					this.SendPropertyChanging();
					this._ID_Movimiento = value;
					this.SendPropertyChanged("ID_Movimiento");
					this.OnID_MovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> Fecha
		{
			get
			{
				return this._Fecha;
			}
			set
			{
				if ((this._Fecha != value))
				{
					this.OnFechaChanging(value);
					this.SendPropertyChanging();
					this._Fecha = value;
					this.SendPropertyChanged("Fecha");
					this.OnFechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movimiento", DbType="NVarChar(10)")]
		public string Movimiento
		{
			get
			{
				return this._Movimiento;
			}
			set
			{
				if ((this._Movimiento != value))
				{
					this.OnMovimientoChanging(value);
					this.SendPropertyChanging();
					this._Movimiento = value;
					this.SendPropertyChanged("Movimiento");
					this.OnMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MontoTotal", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> MontoTotal
		{
			get
			{
				return this._MontoTotal;
			}
			set
			{
				if ((this._MontoTotal != value))
				{
					this.OnMontoTotalChanging(value);
					this.SendPropertyChanging();
					this._MontoTotal = value;
					this.SendPropertyChanged("MontoTotal");
					this.OnMontoTotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
